// <auto-generated />
using System;
using CNRBShop.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNRBShop.Migrations
{
    [DbContext(typeof(CNRBShopDbContext))]
    [Migration("20230829204130_initiationMigration")]
    partial class initiationMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("CNRBShop.Entities.ProductEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InStock")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsFemale")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsForMan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "vel",
                            Image = "https://picsum.photos/640/480/?image=180",
                            InStock = false,
                            Name = "Incredible Rubber Gloves",
                            Price = 54m
                        },
                        new
                        {
                            Id = 2,
                            Description = "expedita",
                            Image = "https://picsum.photos/640/480/?image=336",
                            InStock = false,
                            Name = "Gorgeous Frozen Towels",
                            Price = 49m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Autem et iusto ipsa quod consequatur ut voluptatibus voluptatibus. Dolorum quidem minima nihil. Magni sit labore blanditiis nostrum.",
                            Image = "https://picsum.photos/640/480/?image=238",
                            InStock = true,
                            Name = "Fantastic Rubber Computer",
                            Price = 50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "reiciendis",
                            Image = "https://picsum.photos/640/480/?image=237",
                            InStock = false,
                            Name = "Generic Fresh Pizza",
                            Price = 49m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Reiciendis ea saepe maiores voluptatum nam est ut. Repudiandae sapiente nostrum aut earum vero aliquid exercitationem aliquid. Dignissimos distinctio voluptatem adipisci quis odit quo culpa assumenda libero. Aut unde corrupti non facere veniam. Delectus impedit accusamus doloribus molestias pariatur eaque. Odit delectus quaerat et ut aut.",
                            Image = "https://picsum.photos/640/480/?image=492",
                            InStock = false,
                            Name = "Awesome Metal Keyboard",
                            Price = 53m
                        },
                        new
                        {
                            Id = 6,
                            Description = "maiores",
                            Image = "https://picsum.photos/640/480/?image=68",
                            InStock = false,
                            Name = "Incredible Soft Salad",
                            Price = 57m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ut ut est consequatur praesentium molestiae qui cum hic.\nEum et ex cumque hic nisi id.\nVoluptas et quis eum.\nNisi est molestiae rerum ut et.\nVel aperiam autem velit illum quae aut aut quo fugiat.",
                            Image = "https://picsum.photos/640/480/?image=735",
                            InStock = false,
                            Name = "Handmade Concrete Ball",
                            Price = 55m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ut optio vel sequi est quia ut.\nAliquam enim aut fugiat ipsam sit at nulla.\nConsequatur eum quis.\nRepellat explicabo non dolore.\nVoluptates aut sed quia mollitia eum placeat.",
                            Image = "https://picsum.photos/640/480/?image=778",
                            InStock = true,
                            Name = "Gorgeous Plastic Table",
                            Price = 56m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Voluptatibus et impedit.",
                            Image = "https://picsum.photos/640/480/?image=59",
                            InStock = true,
                            Name = "Unbranded Cotton Bacon",
                            Price = 49m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Et illum ut nihil delectus non impedit et.",
                            Image = "https://picsum.photos/640/480/?image=265",
                            InStock = false,
                            Name = "Rustic Cotton Cheese",
                            Price = 52m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
